<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LogicPower2" name="info.uaua.TestObjavlinija" tests="8" failures="0" timestamp="29 Apr 2015 13:09:54 GMT" time="146.703" errors="1">
  <testcase name="testAd07" time="0.582" classname="info.uaua.TestObjavlinija"/>
  <testcase name="testAd02" time="10.943" classname="info.uaua.TestObjavlinija"/>
  <testcase name="testAd06" time="34.246" classname="info.uaua.TestObjavlinija"/>
  <testcase name="testAd04" time="37.782" classname="info.uaua.TestObjavlinija"/>
  <testcase name="testAd08" time="3.425" classname="info.uaua.TestObjavlinija">
    <error type="java.lang.AssertionError" message="expected:&lt;86&gt; but was:&lt;113&gt;">
      <![CDATA[java.lang.AssertionError: expected:<86> but was:<113>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)
	at info.uaua.ObjavlinijaObjects.findAddedObyavlenia(ObjavlinijaObjects.java:75)
	at info.uaua.TestObjavlinija.testAd08(TestObjavlinija.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testAd08 -->
  <testcase name="testAd01" time="13.206" classname="info.uaua.TestObjavlinija"/>
  <testcase name="testAd03" time="35.334" classname="info.uaua.TestObjavlinija"/>
  <testcase name="testAd05" time="11.185" classname="info.uaua.TestObjavlinija"/>
</testsuite> <!-- info.uaua.TestObjavlinija -->
